package org.derecalliance.derec.api;

import java.net.URI;

public interface DeRecContact {
    /**
     * @return public encryption key
     */
    String getPublicEncryptionKey();

    /**
     * @return public encryption id
     */
    int getPublicEncryptionKeyId();

    /**
     * @return transport URI
     */
    URI getTransportUri();

    /**
     * @return nonce to identify pairing session
     */
    long getNonce();

    /**
     * Creates the contact message about a user
     *
     * @param publicEncryptionKeyId publicEncryptionKeyId of the user
     * @param publicEncryptionKey   publicEncryptionKey of the user
     * @param nonce                 nonce generated by the user
     * @param transportUri          transportUri of the user
     * @return byte[] Serialized contact
     */
    public byte[] createContactMessage(int publicEncryptionKeyId, String publicEncryptionKey, long nonce, URI transportUri);

    /**
     * Parses the contact message received from a user
     *
     * @param data Serialized contact
     * @return DeRecContact object
     */
    public DeRecContact parseContactMessage(byte[] data);
}

