name: Publish package to GitHub Packages
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Java
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # delete all old -SNAPSHOT versions except 1
      - name: Delete old snapshot versions
        uses: actions/delete-package-versions@0d39a63126868f5eefaa47169615edd3c0f61e20 # v4.1.1
        with: 
          package-name: 'org.derecalliance.derec.derec-api'
          package-type: 'maven'
          min-versions-to-keep: 1
          ignore-versions: '^(?!.*-SNAPSHOT).*$'
